### PR TITLE
use latest release version of metrics

### PR DESCRIPTION
**Pull request by davidkarlsen**
Could you do a release soon so that new outputs (ganglia/graphite) could be supported and use features from metrics 3.1.1?

### CODE REVIEW

**Comment by cemo** [comment]
+1

**Comment by davidkarlsen** [comment]
Ping. Is this project still active?

**Comment by ryantenney** [comment]
@davidkarlsen This version supports graphite and ganglia reporters, and it fully supports 3.1.1, it just isn't compiled against it. I aim to get a new version out soon, but I have a couple other fixes I need to make before I bump the version.

**Comment by luolong** [comment]
Any status update?

**Comment by Alexandra12** [comment]
I really need it also ...

**Comment by davidkarlsen** [comment]
This is fixed - closing pull request.

**Pull request closed without merging**
